[loggers]
keys=root,rospy

[handlers]
keys=console,console_debug,file

[formatters]
keys=normal,debug

# Loggers

[logger_root]
level=NOTSET
handlers=console,file

[logger_rospy]
level=WARNING
handlers=console,file
qualname=rospy

# Handlers

[handler_console]
class=StreamHandler
level=INFO
formatter=normal
args=(sys.stdout,)

[handler_console_debug]
class=StreamHandler
level=DEBUG
formatter=debug
args=(sys.stdout,)

[handler_file]
class=logging.handlers.TimedRotatingFileHandler
level=DEBUG
formatter=debug
args=(os.path.expanduser('~/mass.log'), 'midnight',)

# Formatters

[formatter_normal]
class=common.logging.colored_formatter.ColoredFormatter
format=%(levelname).8s (%(asctime)s) %(name)s: %(message)s

[formatter_debug]
class=common.logging.colored_formatter.ColoredFormatter
format=%(levelname).8s (%(asctime)s) %(name)s.%(funcName)s: %(message)s
